<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success'] = array(
        'title' => 'Your DNA!',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['half_helix'] = array(
        '#title' => 'Half Helix',
        '#type' => 'textfield',
        '#attributes' => array('placeholder' => t('Enter Your Half of the Helix to Get Another!')),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_helix'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function element_validate_helix($element) {
    $valid_helix = array('A', 'T', 'C', 'G');

    $helix_array = strtoupper($element['#value']);
    $helix_array = trim($helix_array);
    $helix_array = str_split($helix_array);

    foreach($helix_array as $letter) {
        if (!in_array($letter, $valid_helix)) {
            form_error($element, t('Valid Helix Value Only: A T C or G'));
        }
    }
}

function make_helix($input) {
    $valid_helix = array('A', 'T', 'C', 'G');

    $input_helix_array = str_split($input);
    $output_helix_array = array();

    foreach ($input_helix_array as $letter) {
        $letter = strtoupper($letter);
        if (in_array($letter, $valid_helix)) {
            if ($letter == 'A') {
                array_push($output_helix_array, 'T');
            } elseif ($letter == 'T') {
                array_push($output_helix_array, 'A');
            } elseif ($letter == 'C') {
                array_push($output_helix_array, 'G');
            } elseif ($letter == 'G') {
                array_push($output_helix_array, 'C');
            }
        }
    }
    return implode('', $output_helix_array);
}


function dna_form_submit($form, &$form_state) {
    $input = $form_state['values']['half_helix'];
    $_SESSION['original'] = $input;
    $result = make_helix($input);
    $_SESSION['dna'] = $result;

    $form_state['redirect'] = 'dna_success';
}

function dna_success() {
    $input = $_SESSION['original'];
    $dna = $_SESSION['dna'];
    return '<br><p><strong>Original Helix</strong>: ' . $input . '</p><hr><p><strong>Second Half Helix</strong>: ' . $dna . '</p>';
}
